<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Setting;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class SettingsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            $user = User::first();
            $userId = $user?->id;
            $seedTime = now();

            $settings = [
                [
                    'name' => 'base_price',
                    'value' => '599',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'base_area',
                    'value' => '1500',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'extra_area',
                    'value' => '500',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'extra_area_price',
                    'value' => '200',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'active_payment_gateway',
                    'value' => 'cashfree',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'cashfree_status',
                    'value' => '1',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'payu_status',
                    'value' => '0',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'payu_merchant_key',
                    'value' => '',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'payu_merchant_salt',
                    'value' => '',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'payu_mode',
                    'value' => 'test',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'razorpay_status',
                    'value' => '0',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'razorpay_key',
                    'value' => '',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'razorpay_secret',
                    'value' => '',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'razorpay_mode',
                    'value' => 'test',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'sms_gateway_msg91_status',
                    'value' => '1',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'msg91_auth_key',
                    'value' => '433998AopMixVzR672c8994P1',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'msg91_sender_id',
                    'value' => 'PROPPK',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'msg91_timeout',
                    'value' => '3000',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'avaliable_days',
                    'value' => '45',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'per_day_booking',
                    'value' => '20',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'customer_attempt',
                    'value' => '3',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'customer_attempt_note',
                    'value' => 'You have reached the maximum number of schedule attempts. Please contact admin for further assistance.',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'photographer_available_from',
                    'value' => '08:00',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'photographer_available_to',
                    'value' => '21:00',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'photographer_working_duration',
                    'value' => '60',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'support_email',
                    'value' => 'contact@proppik.com',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'support_phone',
                    'value' => '+91 98 98 36 30 26',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'api_base_url',
                    'value' => 'https://bk.proppik.cloud/api/',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'qr_link_base',
                    'value' => 'https://qr.proppik.cloud/',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 's3_link_base',
                    'value' => 'https://cdn.proppikglobal.in/',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_footer_button_text',
                    'value' => 'Designe By PROP PIK',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_bottommark_contact_text',
                    'value' => 'Designed by PROP PIK',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_bottommark_logo',
                    'value' => 'settings/tour-bottommark/tour_bottommark_logo_1770124807_VgIdQF0a.png',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_footer_button_link',
                    'value' => 'https://www.proppik.com/contact.html',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_footer_link_show',
                    'value' => '1',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_barcode_url',
                    'value' => 'https://www.proppik.com',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_meta_title',
                    'value' => 'PROP PIK: Next Generation AI Web Virtual Reality',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_meta_description',
                    'value' => 'Explore next-gen Web Virtual Reality powered by AI with PROP PiK. Create,view and share interactive virtual property tours instantly and professionally.',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'tour_bottommark_contact_mobile',
                    'value' => '9898363026',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'portfolio_api_enabled',
                    'value' => '1',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'portfolio_api_mobile',
                    'value' => '+917383883362',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'portfolio_api_token_validity_minutes',
                    'value' => '30',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'cloudflare_zone_id',
                    'value' => '71dbf13488372a88e641e854d1ebaab9',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
                [
                    'name' => 'cloudflare_api_token',
                    'value' => 'qY-ki-IsglyRnNtsLIK_oS5aFgVz75a3eYchTRXo',
                    'created_by' => $userId,
                    'updated_by' => $userId,
                    'created_at' => $seedTime,
                    'updated_at' => $seedTime,
                ],
            ];

            foreach ($settings as $setting) {
                Setting::updateOrCreate(
                    ['name' => $setting['name']],
                    $setting
                );
            }
        });
    }
}
