
// Icon Library Modal Logic
export const ICON_LIST = [
    { name: 'facebook', class: 'fa-brands fa-facebook' },
    { name: 'facebook-f', class: 'fa-brands fa-facebook-f' },
    { name: 'facebook-messenger', class: 'fa-brands fa-facebook-messenger' },
    { name: 'instagram', class: 'fa-brands fa-instagram' },
    { name: 'twitter', class: 'fa-brands fa-twitter' },
    { name: 'x-twitter', class: 'fa-brands fa-x-twitter' },
    { name: 'linkedin', class: 'fa-brands fa-linkedin' },
    { name: 'Github', class: 'fa-brands fa-github' },
    { name: 'linkedin-in', class: 'fa-brands fa-linkedin-in' },
    { name: 'youtube', class: 'fa-brands fa-youtube' },
    { name: 'tiktok', class: 'fa-brands fa-tiktok' },
    { name: 'snapchat', class: 'fa-brands fa-snapchat' },
    { name: 'Telegram', class: 'fa-solid fa-paper-plane' },
    { name: 'pinterest', class: 'fa-brands fa-pinterest' },
    { name: 'Discord', class: 'fa-brands fa-discord' },
    { name: 'pinterest-p', class: 'fa-brands fa-pinterest-p' },
    { name: 'reddit', class: 'fa-brands fa-reddit' },
    { name: 'Wordpress', class: 'fa-brands fa-wordpress' },
    { name: 'Slack', class: 'fa-brands fa-slack' },
    { name: 'reddit-alien', class: 'fa-brands fa-reddit-alien' },
    { name: 'whatsapp', class: 'fa-brands fa-whatsapp' },
    { name: 'telegram', class: 'fa-brands fa-telegram' },
    { name: 'discord', class: 'fa-brands fa-discord' },
    { name: 'github', class: 'fa-brands fa-github' },
    { name: 'gitlab', class: 'fa-brands fa-gitlab' },
    { name: 'bitbucket', class: 'fa-brands fa-bitbucket' },
    { name: 'stack-overflow', class: 'fa-brands fa-stack-overflow' },
    { name: 'medium', class: 'fa-brands fa-medium' },
    { name: 'dribbble', class: 'fa-brands fa-dribbble' },
    { name: 'Medium', class: 'fa-brands fa-medium' },
    { name: 'behance', class: 'fa-brands fa-behance' },
    { name: 'figma', class: 'fa-brands fa-figma' },
    { name: 'slack', class: 'fa-brands fa-slack' },
    { name: 'skype', class: 'fa-brands fa-skype' },
    { name: 'google', class: 'fa-brands fa-google' },
    { name: 'apple', class: 'fa-brands fa-apple' },
    { name: 'microsoft', class: 'fa-brands fa-microsoft' },
    { name: 'android', class: 'fa-brands fa-android' },
    { name: 'amazon', class: 'fa-brands fa-amazon' },
    { name: 'spotify', class: 'fa-brands fa-spotify' },
    { name: 'soundcloud', class: 'fa-brands fa-soundcloud' },
    { name: 'vimeo', class: 'fa-brands fa-vimeo' },
    { name: 'twitch', class: 'fa-brands fa-twitch' },
    { name: 'quora', class: 'fa-brands fa-quora' },
    { name: 'yahoo', class: 'fa-brands fa-yahoo' },
    { name: 'yandex', class: 'fa-brands fa-yandex' },
    { name: 'Apple', class: 'fa-brands fa-apple' },
    { name: 'Bookmark Outline', class: 'fa-regular fa-bookmark' },
    { name: 'Cut', class: 'fa-solid fa-cut' },
];
